apiVersion: v1
kind: Service
metadata:
  name: eureka
  labels:
    app:  eureka
    version: v1
spec:
  ports:
    -
      name: http 
      port: 8761      
      targetPort: 8761  
  selector:           
    app: eureka
  type: NodePort       
