apiVersion: v1
kind: Service
metadata:
  name: conversionservice
  labels:
    app:  conversionservice
    version: v1
spec:
  ports:
    -
      name: http 
      port: 8100      
      targetPort: 8100  
  selector:           
    app: conversionservice
  type: NodePort       
  
  