apiVersion: v1
kind: Service
metadata:
  name: zipkin-service-deployment
  labels:
    name: zipkin-service
spec:
  ports:
    - nodePort: 30163 
      port: 9411      
      targetPort: 9411  
      protocol: TCP
  selector:           
    app: zipkin-service
  type: NodePort       
