apiVersion: apps/v1 
kind: Deployment    
metadata:              
  name: zipkin-service-deployment
spec:                
  selector:         
    matchLabels:
      app: zipkin-service
  replicas: 1        
  template:
    metadata:
      labels:        
        app: zipkin-service
    spec:
      containers:
        - name: zipkin-service
          image: pnandi87/zipkinserver
          ports:
            - containerPort: 9411       