apiVersion: v1
kind: Service
metadata:
  name: exchangeservice
  labels:
    app:  exchangeservice
    version: v1
spec:
  ports:
    -
      name: http 
      port: 8000      
      targetPort: 8000  
  selector:           
    app: exchangeservice
  type: NodePort       
  